### PR TITLE
Marcelle

### PR DESCRIPTION
**Pull request by marcelledekock**
changed print statements
included future library
added alternative solutions to certain examples
added maximum peak calculation to utils

### CODE REVIEW

**Comment by alchemyst** [comment]
I am sorry, but I cannot merge code that breaks the tests. You can run the checks that Travis is running by running `runall.py` as well as `utils.py` under Python 2. See [here](http://conda.pydata.org/docs/py2or3.html) for instructions on how to do that. You can investigate the outcome of the tests by clicking [here](https://travis-ci.org/alchemyst/Skogestad-Python/builds/113909547).

**Comment by marcelledekock** [comment]
Sir,

I don't understand why your checks are failing?
I did run runall.py after changing a few things to make it work, and the files that I've changed, committed and submitted the pull request for are successful.
The error that your check is outputting are because of the new true and floor divide functions that need to be specified in utils, which I did change. So I'm not sure what to do.

Regards,
Marcelle

________________________________

**Comment by alchemyst** [comment]
Are you running the tests under python 2?

--
This message may contain unintentional errors, as it was typed on a phone

**Comment by alchemyst** [comment]
My suggestion is to break this pull request into smaller bits. You're adding more files to the PR every time. Branch from master on your repo and just copy one file from your `marcelle` branch to that new one, then do a PR. This way everything stays nicely contained.

I have created a `compatability` branch where the testing runs both 2.7 and 3.5 and will currently fail. I suggest that we use [Python-Future](http://python-future.org/) as our compatability layer and try to get all tests to run in that branch rather than messing with master.

**Comment by alchemyst** [comment]
I've opened #182 for the compatability layer process.

**Pull request closed without merging**
