### PR TITLE
Added list() for addition

### PR DESCRIPTION
**Pull request by adrianrussell559**

### CODE REVIEW

**Comment by alchemyst** [comment]
Thanks for this - I wonder why the tests didn't fail on the previous version? Could you perhaps check and add a test which would fail for this?

**Comment by adrianrussell559** [comment]
Being a noob at this, I'm not sure what exactly you mean by adding a test? Could you perhaps point me in the right direction? thanks.

**Comment by alchemyst** [comment]
We run automated tests using the service travis-ci.org <http://travis-ci.org/>. You can see our test results here: https://travis-ci.org/alchemyst/Skogestad-Python <https://travis-ci.org/alchemyst/Skogestad-Python>

Travis runs the tests as described in the file .travis.yml. In short, it runs the “runall.py” script as well as running utils.py. When you look in utils.py you will see that all the comments with examples are actually checked for correctness by the doctest library https://docs.python.org/3/library/doctest.html <https://docs.python.org/3/library/doctest.html>. This means that we should see things break if we make changes which alter the output of any of the examples in utils.py or if any of the examples, figures and excercises fails to run.

This is an excellent introduction to the idea of automated testing: http://nedbatchelder.com/text/test0.html <http://nedbatchelder.com/text/test0.html>

**Comment by adrianrussell559** [comment]
With regard to this, the original det() fails when I run it on a 3x3 or larger matrix in python3. However, there is a test which makes use of a 3x3 matrix in the docstring, so I'm not sure why that test wasn't failing before the list() function was added.

**Pull request merged**
