### PR TITLE
Rename .py files to .ipynb fix #358

### LINKED ISSUE #358: Convert .py files in reproductions to notebooks
Note that this involves more work than simply converting the .py files to .ipynb. Currently every one of the .py files are part of the testing process, so to complete this task you also have to rework the testing machinery.

The goal is also specifically to _replace_ the .py files with the .ipynb files and not to duplicate them as this increases the maintenance load.

### PR DESCRIPTION
**Pull request by Bern-Alberts**
I did random spot tests with a few of the newly generated files and found no issues.

### CODE REVIEW

**Comment by alchemyst** [comment]
This is a good start, but the goal is to _replace_ the `.py` files with the `.ipynb` files instead of just copying, since that would introduce additional maintenance burden. The full fix here also includes updating the tests to run the `.ipynb` files instead of the `.py` files.

**Comment by alchemyst** [comment]
This might be done more easily by using pytest instead of runall.py, see issue #359 .

**Comment by alchemyst** [comment]
Just so that it links, I'm going to mention the issue #358

**Comment by Bern-Alberts** [comment]
@alchemyst Fixing the environment variable issues with the link you provided got pytest working and all reproduction notebooks have been tested.

I found issues in 3 notebooks that used the 'execfile' function and have replaced this.

All reproduction notebooks passed the subsequent test.

**Comment by alchemyst** [comment]
Thanks for this @Bern-Alberts . Unfortunately this has broken the [tests on Travis](https://travis-ci.org/github/alchemyst/Skogestad-Python). You can check that you're not breaking stuff by enabling Travis builds on your fork.

**Comment by alchemyst** [comment]
Hi @Bern-Alberts . Can you please rebase this work to the current version of the repo? There have been some changes to the Python files which now means I can't automatically merge this.

**Comment by Bern-Alberts** [comment]
@alchemyst Will do

**Comment by Bern-Alberts** [comment]
@alchemyst I wasn't paying attention when updating "environment.yml". I merged in the changes that were made to some reproduction py files and regenerated their respective notebooks.

**Pull request merged**
