### PR TITLE
Master

### PR DESCRIPTION
**Pull request by marcelledekock**
parenthesis changes and include future

### CODE REVIEW

**Comment by alchemyst** [comment]
I'll accept this, but I prefer specifying which features to import from future explicily (in other words use `from __future__ import print_function` rather than just `import __future__`.

**Comment by marcelledekock** [comment]
Any particular reason why you prefer specifics sir?
Isn’t it safer to include everything in case you need it?

**Comment by alchemyst** [comment]
The big reason is that the things in __future__ can change with different versions of Python. So you think your code runs fine, but then you upgrade your python and a new incompatible feature breaks your code. So for example, imagine you imported future just for the division behaviour but before the printing behaviour entered future. Just upgrading your python now breaks all your code. "Explicit is better than implicit” is part of the Zen of Python (do "import this” to see all the rules).

**Comment by alchemyst** [comment]
Another comment: Please use better descriptive names for your pull requests. They all appear to be called "Master" or something like that which has no meaning - how do I tell them apart?

**Pull request merged**
