### PR TITLE
Master

### PR DESCRIPTION
**Pull request by hlayisib**
Fixed plot labels

### CODE REVIEW

**Comment by alchemyst** [comment]
Please add `from __future__ import print_function` at the top of Example 3.10 otherwise it will not run in Python 2

**Comment by hlayisib** [comment]
I only did example 5.12 and thats the one I submitted a pull request for

**Comment by alchemyst** [comment]
Unfortunately a pull request will include all the changes you have made, you can't only select one file for the pull request. You can see which files are affected by going to the [Files Changed](https://github.com/alchemyst/Skogestad-Python/pull/190/files) section of the PR.

**Comment by hlayisib** [comment]
Thanks. I have done the changes

**Pull request closed without merging**
